$plugins = @(
   'jquerry',
   'pollyfill',
   # 'materializeicons', #css only
   'autosize',
   'ripple',
   'parsley',
   # 'bootstrap',
   'bootstrap-full',
   'jquerry-accordance',
   'lightpick',
   # 'chartjs',
   'select2',
   'datatables',
   'cleave',
   'scrollspy',
   'materialize',
   'Jquery-zoom',
   'light-gallery',
   'swiper',
   'stickup',
   'parallax-js',
   'star-rating',
   'sortable',
   'dropzone',
   'lazyload',
   'shave'
)